apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: test-backend
          image: asdutoit/go_backend:0.0.3
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: test-backend-configmap
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: test-backend-configmap
                  key: DB_PORT
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: test-backend-configmap
                  key: AWS_REGION
            - name: AWS_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: test-backend-configmap
                  key: AWS_S3_BUCKET
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: test-backend-configmap
                  key: FRONTEND_URL
            - name: SECURE_ENV
              valueFrom:
                configMapKeyRef:
                  name: test-backend-configmap
                  key: SECURE_ENV
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: test-backend-configmap
                  key: ENV
            # === SECRETS ===
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: test-backend-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: test-backend-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: test-backend-secrets
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-backend-secrets
                  key: DB_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: test-backend-secrets
                  key: DB_USER
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: test-backend-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: test-backend-secrets
                  key: GOOGLE_CLIENT_ID
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: test-backend-secrets
                  key: SECRET
