name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: <your-ecr-registry>
  ECR_REPOSITORY: <your-ecr-repository>
  AWS_REGION: <your-aws-region>

jobs:
  build-and-push-to-ecr:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-region: af-south-1
          role-to-assume: arn:aws:iam::213705928839:role/gha_oidc_assume_role
          role-session-name: temp-gha-session

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: go-backend
          IMAGE_TAG: ${{ github.sha }}
          ARCH: ${{ matrix.arch }}
        run: |
          docker build --no-cache --platform linux/$ARCH -f Section11-Project/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
